start "all" python backend-api/allDetails.py
start "chapter" python backend-api/chapter.py
start "class" python backend-api/class.py
start "classChapter" python backend-api/classChapter.py
start "course" python backend-api/course.py
start "quiz" python backend-api/quiz.py
start "gradedQuiz" python backend-api/gradedQuiz.py
start "learner" python backend-api/learner.py
start "material" python backend-api/material.py
start "staff" python backend-api/staff.py
start "trainer" python backend-api/trainer.py
start "takeClass" python backend-api/takeClass.py