
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run Integration Tests

on:
  push:
     
  pull_request:
    

jobs:
  build:
    runs-on: ubuntu-latest
    services:
    mysql:
    image: mysql:5.7
    env:
      DB_DATABASE: spm_proj
      DB_USER: root
      DB_HOST: localhost
      DB_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: password
rking-directory: ./backend-api

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set up MySQL
        run: |
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e 
      - name: Test with unittest
        run: |
          python -m unittest backend-api/test_Chapter.py
          python -m unittest backend-api/test_Material.py
          python -m unittest backend-api/test_Course_Integration.py

