
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run Integration Tests

on:
  push:
     
  pull_request:
    

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_DATABASE: spm_proj
      DB_USER: root
      DB_HOST: localhost
    defaults:
      run:
        working-directory: ./backend-api
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE spm_proj;' -uroot -proot
          mysql -e 'SHOW DATABASES;' -uroot -proot
      - name: Test with unittest
        run: |
          python -m unittest test_Chapter.py
          python -m unittest test_Material.py
