
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run Python Tests

on:
  push:
     
  pull_request:
    
services:
  mysql:
    env:
      MYSQL_DATABASE: spm_proj
      MYSQL_USER: root
    ports:
      - 3306


jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend-api
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ../requirements.txt
    - name: Test with unittest
      run: |
        python -m unittest test_Chapter.py
        python -m unittest test_Class.py
        python -m unittest test_Material.py
        python -m unittest test_Quiz.py
